### ISSUE TITLE
推理结果无法显示问题

### ISSUE THREAD

**Issue by nigeiwo** [Kevinnan-teen/Intelligent-Traffic-Based-On-CV#1]
您好，我在服务器上运行该项目，无法显示推理后的视频，定位错误发现多进程读取视频时，并没有读取视频，您运行的时候也是这样吗？

**Comment by Kevinnan-teen** [comment]
你好，第二版代码的视频推流部分是通过SRS服务器实现，没有视频的原因可能是因为你没有搭建SRS服务器。
