### ISSUE TITLE
运行server.selector.py时报错

### ISSUE THREAD

**Issue by Toolsboy1** [Kevinnan-teen/Intelligent-Traffic-Based-On-CV#4]
你好，当我运行server.selector.py时，成功监听本地127.0.0.1 10001后，开始waiting for I/O，当代码运行到和rtmp服务器连接成功返回cap init is completed后，就报can't pickle _thread.lock objects，如下图所示：
![image](https://user-images.githubusercontent.com/61649826/170154533-9772bc2b-4042-472f-97fd-7a2c5ffedc87.png)

当我把process.start()改为process.run()后，代码可以跑，但是似乎无法开启多进程，只会一直返回waiting for I/O。

不知道您当时有没有遇到这个问题，希望能得到您的回复。

**Comment by Kevinnan-teen** [comment]
把`print('waiting for I/O')`注释掉，再看看readVideo()是否在读取视频帧，打印看看是否有数据
